"use client";
// import "./globals.css";

import { Inter } from "next/font/google";
import AppHeader from "@/components/app.header";
import AppFooter from "@/components/app.footer";
import Container from "react-bootstrap/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Layout UI */}
      {/* Place children where you want to render a page or nested layout */}
      <body className={inter.className}>
        <AppHeader />
        <Container>{children}</Container>
        <AppFooter />
      </body>
    </html>
  );
}
