import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Layout UI */}
      {/* Place children where you want to render a page or nested layout */}
      <body className={inter.className}>
        <header>Header welcome to</header>
        {children}
        <footer>footer welcome to</footer>
      </body>
    </html>
  );
}
